mkDir build
cd build
cmake .. -G "Visual Studio 16 2019" -A x64 -DUSE_EUCLID_ALL_OPTIMIZATIONS=ON -DUSE_CLIP_SPACE_ZERO_TO_ONE=ON -DUSE_SCREEN_SPACE_UPPER_LEFT_ORIGIN=OFF -DUSE_LEFT_HANDED_COORDINATE_SYSTEM=OFF
pause